services:
  ap_proxy:
    container_name: ap_proxy
    build: ./proxy
    tty: true
    restart: always
  ap_webpilot:
    container_name: ap_webpilot
    depends_on:
      - ap_proxy
      - ap_postgres
    build: ./webpilot
    tty: true
    ports:
      - "58000:58000/tcp"
    restart: always
  ap_postgres:
    container_name: ap_postgres
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - rdb_data:/var/lib/posrgresql/data
    ports:
      - "5432:5432/tcp"
    restart: always
  ap_redis:
    container_name: ap_redis
    image: redis:7.0.5
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379/tcp"
    restart: always
volumes:
  rdb_data: {}
  redis_data: {}
